server:
  port: 8088
  servlet:
    context-path: /

spring:
  data:
    jdbc:
      repositories:
        enabled: false
  application:
    name: bumble-bee-loan-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
      hbm2ddl:
        import_files: data.sql
    open-in-view: false
  datasource:
    url: jdbc:mysql://bumblebee.mysql.database.azure.com:3306/bumblebee_store?useSSL=true
    username: bumblebee
    password: Admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    enabled: true
    operationsSor ter: method
    path: /swagger-ui.html
