name: Azure Web App Deployment

on:
  push:
    branches:
      - feature/github-action-code

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn package --file pom.xml

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure Web App Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bumblebee-webapi'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_6dc10b2dc6894a9a8fe23e8363f23d71 }}
          package: target/*.jar